config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "contacts#index"
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, length: { maximum: 50 }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, length: { maximum: 50 }
  validates :telephone, presence: true, numericality: { only_integer: true }, length: {in: 10..15}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
    @contacts = Contact.where(['last_name LIKE ?', "%#{params[:search]}%"]) if params[:search]
    @search = params[:search]
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :telephone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<div class="container text-bg-light p-3">
  <h2>Edit Contact</h2>

  <%= form_with model: @contact do |form| %>
    <div>
      <%= form.label :first_name, :class => 'form-label' %><br>
      <%= form.text_field :first_name, :class => 'form-control form-control-lg' %>
      <% @contact.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :last_name, :class => 'form-label' %><br>
      <%= form.text_field :last_name, :class => 'form-control form-control-lg' %>
      <% @contact.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :telephone, :class => 'form-label' %><br>
      <%= form.text_field :telephone, :class => 'form-control form-control-lg', :type => 'tel' %>
      <% @contact.errors.full_messages_for(:telephone).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.button "Edit", type: "submit", :class=> "btn btn-primary btn-lg mt-4" %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="container text-bg-light p-3">
    <div class="d-flex justify-content-between mb-4">
      <h2 class="d-inline">Contacts</h2>
      <%= link_to "+ Add Contact", new_contact_path, class: "btn btn-primary btn-lg" %>
    </div>

    <div class="mb-3">
      <i class="fa fa-search"></i>
      <%= text_field_tag 'search', @search, id: "search", data: {'js-search' => true}, class: "form-control", placeholder: "Search for contact by last name..."%>
    </div>

    <ul class="list-group">
      <% @contacts.each do |contact| %>
        <li  class="list-group-item d-flex justify-content-between p-4">
          <div>
            <div class="fw-bold">
              <%= contact.first_name %> <%= contact.last_name %>
            </div>
            <div class="text-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
              </svg>
              <%= contact.telephone %>
            </div>
          </div>
          <div>
            <%= link_to edit_contact_path(contact), class: "btn btn-success btn-lg" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
              </svg>
            <% end %>
            <%= link_to contact_path(contact), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"
            }, class: "btn btn-danger btn-lg" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
              </svg>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
</div>

<script>
    $(document).ready(function() {
        $('#search').change(function() {
            var search_term = $(this).val();
            Turbo.visit("?search=" + search_term, { action: "replace" })
        })
        .keyup(function(event) {
            if (event.keyCode === 13) {
                var search_term = $(this).val();
                Turbo.visit("?search=" + search_term, { action: "replace" })
            }
        });
    });
</script>

app/views/contacts/new.html.erb
<div class="container text-bg-light p-3">
  <h2>New Contact</h2>

  <%= form_with model: @contact do |form| %>
    <div>
      <%= form.label :first_name, :class => 'form-label' %><br>
      <%= form.text_field :first_name, :class => 'form-control form-control-lg' %>
      <% @contact.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :last_name, :class => 'form-label' %><br>
      <%= form.text_field :last_name, :class => 'form-control form-control-lg' %>
      <% @contact.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :telephone, :class => 'form-label' %><br>
      <%= form.text_field :telephone, :class => 'form-control form-control-lg', :type => 'tel' %>
      <% @contact.errors.full_messages_for(:telephone).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.button "Add Contact", type: "submit", :class=> "btn btn-primary btn-lg mt-4" %>
    </div>
  <% end %>
</div>

app/views/contacts/show.html.erb
<h1><%= @contact.first_name %></h1>
<p><%= @contact.last_name %></p>

<ul>
  <li><%= link_to "Edit", edit_contact_path(@contact) %></li>
  <li><%= link_to "Destroy", contact_path(@contact), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneBookApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "jquery", "data-turbolinks-track" => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>